In [1]:
import numpy as np
np_arr = np.random.seed(101) 

In [2]:
np_arr

In [3]:
print(np_arr)

None


In [4]:
arr = np.random.randint(0,100,10)

In [5]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [6]:
arr.max

<function ndarray.max>

In [7]:
arr.max()

95

In [8]:
arr.min()

9

In [9]:
arr.data

In [10]:
arr.mean

<function ndarray.mean>

In [11]:
arr.mean()

60.8

In [12]:
arr.argmax()

0

In [13]:
arr.argmin()

7

In [15]:
help(arr.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [16]:
arr.reshape(1,5)

ValueError: cannot reshape array of size 10 into shape (1,5)

In [17]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [18]:
matrix_one = np.arange(0,50).reshape(10,5)

In [19]:
matrix_one

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [22]:
matrix_one.dtype

dtype('int32')

In [24]:
matrix_one[:3]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
matrix_one[3:3]

array([], shape=(0, 5), dtype=int32)

In [26]:
matrix_one[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
matrix_one[3,3]

18

In [29]:
matrix_one[1:3,1:3]

array([[ 6,  7],
       [11, 12]])